/**
 * Auto-generated OpenAPI Specification
 * 
 * This file is auto-generated by scripts/generate-openapi.js
 * Do not edit manually - run: node scripts/generate-openapi.js
 */

export const autoOpenApiOptions = {
  "openapi": "3.0.3",
  "info": {
    "title": "Converge API",
    "description": "Converge API - Auto-generated from route files. Run 'node scripts/generate-openapi.js' to regenerate.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "/api",
      "description": "Current server"
    }
  ],
  "tags": [
    {
      "name": "Admin",
      "description": "Admin endpoints"
    },
    {
      "name": "AI",
      "description": "AI endpoints"
    },
    {
      "name": "Chat",
      "description": "Chat endpoints"
    },
    {
      "name": "External",
      "description": "External endpoints"
    },
    {
      "name": "Health",
      "description": "Health endpoints"
    },
    {
      "name": "Heimdall",
      "description": "Heimdall endpoints"
    },
    {
      "name": "Internal",
      "description": "Internal endpoints"
    },
    {
      "name": "Issues",
      "description": "Issues endpoints"
    },
    {
      "name": "Logs",
      "description": "Logs endpoints"
    },
    {
      "name": "Metrics",
      "description": "Metrics endpoints"
    },
    {
      "name": "Mobile",
      "description": "Mobile endpoints"
    },
    {
      "name": "Notifications",
      "description": "Notifications endpoints"
    },
    {
      "name": "Openapi",
      "description": "Openapi endpoints"
    },
    {
      "name": "Ops",
      "description": "Ops endpoints"
    },
    {
      "name": "Redmine",
      "description": "Redmine endpoints"
    },
    {
      "name": "Reports",
      "description": "Reports endpoints"
    },
    {
      "name": "Saved Views",
      "description": "Saved Views endpoints"
    },
    {
      "name": "Search",
      "description": "Search endpoints"
    },
    {
      "name": "Session",
      "description": "Session endpoints"
    },
    {
      "name": "Slack",
      "description": "Slack endpoints"
    },
    {
      "name": "Sync",
      "description": "Sync endpoints"
    },
    {
      "name": "Time Entries",
      "description": "Time Entries endpoints"
    },
    {
      "name": "Wakatime",
      "description": "Wakatime endpoints"
    },
    {
      "name": "Webhooks",
      "description": "Webhooks endpoints"
    }
  ],
  "paths": {
    "/admin/users/{id}/role": {
      "patch": {
        "tags": [
          "Admin"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          },
          {
            "name": "0",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: 0"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/categorize": {
      "post": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/chat": {
      "get": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "redmineIssueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "redmineIssueId"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "redmineIssueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "redmineIssueId"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "redmineIssueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "redmineIssueId"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/search": {
      "post": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/status": {
      "get": {
        "tags": [
          "AI"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/summarize": {
      "get": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "issueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "issueId"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "AI"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "issueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "issueId"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/ai/summary-count": {
      "get": {
        "tags": [
          "AI"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/chat/execute-tools": {
      "post": {
        "tags": [
          "Chat"
        ],
        "summary": "POST /api/chat/execute-tools",
        "description": "POST /api/chat/execute-tools",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/chat": {
      "get": {
        "tags": [
          "Chat"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Chat"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/external/tickets/{id}": {
      "get": {
        "tags": [
          "External"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          },
          {
            "name": "api_key",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "api_key"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/external/tickets": {
      "get": {
        "tags": [
          "External"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "api_key"
          },
          {
            "name": "search",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "search"
          },
          {
            "name": "redmineId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "redmineId"
          },
          {
            "name": "status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "status"
          },
          {
            "name": "project",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "project"
          },
          {
            "name": "assignee",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "assignee"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "offset"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/health": {
      "get": {
        "tags": [
          "Health"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/heimdall/refresh": {
      "post": {
        "tags": [
          "Heimdall"
        ],
        "summary": "Refresh Streamline logs directly from Streamline API into Supabase.",
        "description": "Refresh Streamline logs directly from Streamline API into Supabase.",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/internal/activities": {
      "get": {
        "tags": [
          "Internal"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/internal/notes/{id}": {
      "patch": {
        "tags": [
          "Internal"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Internal"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/internal/notes": {
      "get": {
        "tags": [
          "Internal"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "issueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "issueId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Internal"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "issueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "issueId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/internal/priorities": {
      "get": {
        "tags": [
          "Internal"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/internal/users": {
      "get": {
        "tags": [
          "Internal"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/issues/{id}/assign": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/{id}/attachments/{attachmentId}": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/{id}/attachments": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "refresh",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "refresh"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "refresh",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "refresh"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/{id}/comment": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/{id}/edit": {
      "put": {
        "tags": [
          "Issues"
        ],
        "summary": "PUT",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/{id}/favorite": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/issues/{id}/github-links/{linkId}": {
      "delete": {
        "tags": [
          "Issues"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/{id}/github-links": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      },
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/{id}/refresh": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/issues/{id}/relations/{relationId}": {
      "delete": {
        "tags": [
          "Issues"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/{id}/relations": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/issues/[id]": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: key"
          },
          {
            "name": "fresh",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "fresh"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/issues/{id}/status": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      },
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/{id}/timelog": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/bulk-status": {
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/issues/favorites": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/issues/local/{id}": {
      "patch": {
        "tags": [
          "Issues"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Issues"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/issues/local": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "status"
          },
          {
            "name": "tracker",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "tracker"
          },
          {
            "name": "priority",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "priority"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Issues"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "status"
          },
          {
            "name": "tracker",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "tracker"
          },
          {
            "name": "priority",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "priority"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/issues": {
      "get": {
        "tags": [
          "Issues"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "number",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: number"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/logs": {
      "get": {
        "tags": [
          "Logs"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "level",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "level"
          },
          {
            "name": "source",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "source"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "olderThan",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "olderThan"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Logs"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "level",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "level"
          },
          {
            "name": "source",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "source"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "olderThan",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "olderThan"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Logs"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [
          {
            "name": "level",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "level"
          },
          {
            "name": "source",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "source"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "olderThan",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "olderThan"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "tags": [
          "Metrics"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/mobile/tokens/{id}": {
      "delete": {
        "tags": [
          "Mobile"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/tokens": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/mobile/v1/activities": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/assign": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/attachments/{attachmentId}": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/attachments": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/breadcrumbs": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/comment": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/edit": {
      "put": {
        "tags": [
          "Mobile"
        ],
        "summary": "PUT",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/favorite": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/github-links/{linkId}": {
      "delete": {
        "tags": [
          "Mobile"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/github-links": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      },
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/internal-notes": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/relations/{relationId}": {
      "delete": {
        "tags": [
          "Mobile"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/relations": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/status": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/{id}/time-entries": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues/assignable-users": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/issues": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "number",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: number"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/me": {
      "get": {
        "tags": [
          "Mobile"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/pair/connect": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/mobile/v1/time-entries/{id}": {
      "patch": {
        "tags": [
          "Mobile"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "Mobile"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/tokens/current": {
      "delete": {
        "tags": [
          "Mobile"
        ],
        "summary": "DELETE",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/mobile/v1/tokens/rotate": {
      "post": {
        "tags": [
          "Mobile"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/notifications": {
      "get": {
        "tags": [
          "Notifications"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/openapi": {
      "get": {
        "tags": [
          "Openapi"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/ops/jobs": {
      "post": {
        "tags": [
          "Ops"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/redmine/bootstrap": {
      "get": {
        "tags": [
          "Redmine"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "tags": [
          "Redmine"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/redmine/connect": {
      "post": {
        "tags": [
          "Redmine"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/reports": {
      "get": {
        "tags": [
          "Reports"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "1",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: 1"
          },
          {
            "name": "days",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "days"
          },
          {
            "name": "issueId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "issueId"
          },
          {
            "name": "from",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "from"
          },
          {
            "name": "to",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "to"
          },
          {
            "name": "assignees",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "assignees"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/saved-views/[id]": {
      "patch": {
        "tags": [
          "Saved Views"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Saved Views"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/saved-views": {
      "get": {
        "tags": [
          "Saved Views"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Saved Views"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "0",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: 0"
          },
          {
            "name": "q",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "q"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "offset"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/session/me": {
      "get": {
        "tags": [
          "Session"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Session"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/slack/messages": {
      "get": {
        "tags": [
          "Slack"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          },
          {
            "name": "channelId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "channelId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/slack/notify": {
      "get": {
        "tags": [
          "Slack"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Slack"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/slack/test": {
      "post": {
        "tags": [
          "Slack"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/slack/thread": {
      "get": {
        "tags": [
          "Slack"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          },
          {
            "name": "channelId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "channelId"
          },
          {
            "name": "threadTs",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "threadTs"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/sync/jobs": {
      "get": {
        "tags": [
          "Sync"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "limit"
          },
          {
            "name": "status",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "status"
          },
          {
            "name": "jobType",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "jobType"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/sync/manual-pull": {
      "post": {
        "tags": [
          "Sync"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          }
        }
      }
    },
    "/sync/status": {
      "get": {
        "tags": [
          "Sync"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/time-entries/[id]": {
      "patch": {
        "tags": [
          "Time Entries"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "delete": {
        "tags": [
          "Time Entries"
        ],
        "summary": "PATCH",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/time-entries": {
      "get": {
        "tags": [
          "Time Entries"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/wakatime/stats": {
      "get": {
        "tags": [
          "Wakatime"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "0",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: 0"
          },
          {
            "name": "range",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            },
            "description": "range"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "429": {
            "description": "Rate Limited"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/webhooks/subscriptions/{id}": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "patch": {
        "tags": [
          "Webhooks"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": [
          "Webhooks"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "URL: id"
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/webhooks/subscriptions": {
      "get": {
        "tags": [
          "Webhooks"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "GET",
        "description": "",
        "parameters": [],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/webhooks/test": {
      "post": {
        "tags": [
          "Webhooks"
        ],
        "summary": "POST",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  }
};

export default autoOpenApiOptions;
